config/routes.rb
FriendInTown::Application.routes.draw do
  resources :ratings, :only => [:show, :edit, :update, :destroy]
  resources :feedbacks

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :places
  resources :tours do
    collection do
      get 'popular', :as => "popular_tours"
    end
    resources :ratings, :only => [:create]
    resources :stops
  end
  resources :stops

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'

  match '/contact/send', :to => 'pages#send_contact'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  match '/yc',      :to => 'pages#yc'

  match '/mobile',    :to => 'pages#mobile'

  root :to => 'pages#home'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  after_save :update_rating_cache
  attr_accessible :score, :comment

  belongs_to :tour
  belongs_to :user

  validates :tour, :presence => true
  validates :user, :presence => true
  validates :comment, :presence => true,
                      :length   => { :minimum => 5 }
  validates :score, :presence     => true,
                    :numericality => { :greater_than => 0,
                                       :less_than => 6 }

  VALID_RATINGS = (1..5).to_a

  def as_json(options = {})
    {
      :id      => self.id,
      :tour    => self.tour.id,
      :user    => self.user.id,
      :score   => self.score,
      :comment => self.comment
    }
  end

  private
    def update_rating_cache
      self.tour.update_rating
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :authorized_user, :only => [:edit, :update, :destroy]

  # GET /ratings/1
  # GET /ratings/1.xml
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])
    @title = "Rating details"
    @user = @rating.user

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
      format.json  { render :json => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
      format.json  { render :json => @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.xml
  def create
    @tour = Tour.find_by_url(params[:tour_id])
    @rating = @tour.ratings.build(params[:rating])
    @rating.user = current_user

    respond_to do |format|
      if @rating.save
        format.html { redirect_to(@tour, :notice => 'Rating was successfully created.') }
        format.xml  { render :xml => @tour, :status => :created, :location => @rating }
        format.json  { render :json => @tour, :status => :created, :location => @rating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tour.errors, :status => :unprocessable_entity }
        format.json  { render :json => @tour.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to(@rating, :notice => 'Rating was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
        format.json  { render :json => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating = Rating.find(params[:id])
    @tour = @rating.tour
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to(@tour) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end
  
  private
    def authorized_user
      @rating = current_user.ratings.find_by_id(params[:id])
      redirect_to root_path if @rating.nil?
    end
end

app/views/ratings/_existing_and_new.html.erb
<% if tour.ratings.empty? %> 
<h2>No ratings yet</h2>
<% else %>
<h2><%= pluralize tour.ratings.count, "rating" %></h2>
<%= render tour.ratings %>
<% end %>

<h2>Leave a rating</h2>
<%= form_for([tour, tour.ratings.new]) do |f| %>
  <%= render 'ratings/form_fields', :f => f %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/_form.html.erb
<%= form_for([@tour, @rating]) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'ratings/form_fields', :f => f %>

  <div class="actions">
    <%= f.submit %>
  </div>

  <%= render 'tours/tour_detail', :tour => @rating.tour %>

<% end %>

app/views/ratings/_form_fields.html.erb
<div class="field">
  <%= f.label :score %><br />
  <% Rating::VALID_RATINGS.each do |n| %>
    <%= radio_button "rating", :score, n %>
    <%= label_tag "rating_score_#{n}", n %>
  <% end %>
</div>
<div class="field">
  <%= f.label :comment %><br />
  <%= f.text_area :comment %>
</div>

app/views/ratings/_rating.html.erb
<div class="rating">
  <div>
    <%= pluralize(rating.score, "star") %> By <%= link_to rating.user.name, rating.user %>
  </div>
  <p class="content">
    <%= rating.comment %>
  </p>
</div>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%# link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Tour</th>
    <th>Score</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.user_id %></td>
    <td><%= rating.tour_id %></td>
    <td><%= rating.score %></td>
    <td><%= rating.comment %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<%= render 'form' %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rating.user_id %>
</p>

<p>
  <b>Tour:</b>
  <%= @rating.tour_id %>
</p>

<p>
  <b>Score:</b>
  <%= @rating.score %>
</p>

<p>
  <b>Comment:</b>
  <%= @rating.comment %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%# link_to 'Back', ratings_path %>